# YOUR NAME OR TITLE OF YOUR SITE
name: Nabeel Valley

# YOUR BRAND/PERSONAL TAGLINE
tagline: Software Engineer, Photographer


# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:
  - Name: Website
    URL: https://nabeelvalley.co.za
    Icon-Class: fas fa-link
    Color: '#e44d90'
    Text_Color: '#ffffff'

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: nabeelvalley
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: not_nabeel
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter
    
    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: nabeelvalley
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: nabeelvalley
    Color: '#6e5494'
    Icon-Class: fab fa-github
    # DEV.TO
  - Name: Dev.to
    URL: 'https://dev.to'
    Username: nabeelvalley
    Icon-Class: fab fa-dev
    Color: '#ffffff'
    Text_Color: '#000000'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
